version: 2
sources:
  - name: raw
    schema: SQL_staffanake
    description: data from GZ Enterprise
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales table
        columns:
          - name: date_date
            description: Date of the sales 
          - name: orders_id
            description: joint primary key of the table
          - name: pdt_id
            description: joint primary key of the table
          - name: revenue
            description: Revenue from the sale
          - name: quantity
            description: Quantity sold

      - name: product
        identifier: raw_product
        description: Product table
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: Purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: Shipping table
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: Shipping fee
          - name: shipping_fee_1
            description: Additional shipping fee
          - name: logCost
            description: Logistics cost
          - name: ship_cost
            description: Shipping cost
