version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: data from GZ Enterprise
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales table
        columns:
          - name: date_date
                 ,orders_id
            description: joint primary key of the table
          - name: pdt_id
            description: joint primary key of the table
          - name: revenue
          - name: quantity
            description: quantities sold


      - name: product
        identifier: raw_product
        description: Product table
        columns:
          - name: products_id
            description: Primary key of the table
          - name: purchSE_PRICE
            description: Purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: Shipping table
        columns:
          - name: orders_id
            description: Primary key of the table
          - name: shipping_fee
          - name: shipping_fee_1
            description: additional shipping fee
          - name: logCost
          - name: ship_cost

      - name: adverts
        identifier: raw_gz_adwords
        description: adverts_table
        columns:
          - name: date_date
                  ,paid_source
                  ,campaign_key
                  ,camPGN_name
                  ,ads_cost
                  ,impression
                  ,click
      - name: bing
        identifier: raw_gz_bing
        description: bing_table
        columns:
          - name: date_date
                  ,paid_source
                  ,campaign_key
                  ,camPGN_name
                  ,ads_cost
                  ,impression
                  ,click
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo_ads
        columns:
          - name: date_date
                  ,paid_source
                  ,campaign_key
                  ,camPGN_name
                  ,ads_cost
                  ,impression
                  ,click
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook_ads
        columns:
          - name: date_date
                  ,paid_source
                  ,campaign_key
                  ,camPGN_name
                  ,ads_cost
                  ,impression
                  ,click
